lightbend-labs/mima

reporter/functional-tests/src/test/class-added-local-method-ok/v1/A.scala
reporter/functional-tests/src/test/class-added-local-method-ok/v2/A.scala
reporter/functional-tests/src/test/class-removed-local-method-ok/v1/A.scala
reporter/functional-tests/src/test/class-removed-local-method-ok/v2/A.scala

Tests showing adding/removing local methods is a binary compatible evolution

---

README.md
project/Build.scala
project/build.properties
project/plugins.sbt

This PR is an updated version of https://github.com/typesafehub/migration-manager/pull/63
Fix  #61

Publish sbt plugin to bintray

---

project/Build.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala

Resolves #16
Builds on top of https://github.com/typesafehub/migration-manager/pull/63
Can be tested by
```
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.1-695c6b81a6962c726983c667eb3393b4840f8f39")
resolvers += Resolver.url("2m-sbt-plugins", url("https://dl.bintray.com/2m/sbt-plugins/"))(Resolver.ivyStylePatterns)
```

Check against multiple versions

---

.travis.yml
LICENSE
README.md
core-ui/src/main/resources/LICENSE
core/src/main/resources/LICENSE
core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
project/Build.scala
project/build.properties
project/plugins.sbt
reporter-ui/src/main/resources/LICENSE
reporter/src/main/resources/LICENSE
reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/Analyzer.scala
sbtplugin/src/main/resources/LICENSE

build, dependency, CI, doc improvements

---

core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/template/TemplateRules.scala

Implemented equality contract for ClassInfo. Fix #74

Implemented equality contract for ClassInfo. Fix #74 

---

project/Build.scala

green community build run with these changes:
https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/97/console
review by @dotta

changes helpful for adding MiMa to community build

---

README.md

ref https://github.com/typesafehub/migration-manager/pull/95

remove reporter-ui from README

---

sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala

Conservative, initial port to an AutoPlugin

---

sbtplugin/src/sbt-test/sbt-mima-plugin/backward-abstract-method/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-abstract-method/project/plugins.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-abstract-method/src/main/A.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-abstract-method/src/v1/A.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-abstract-method/test

This is a failing test that illustrates the issue that was found trying out MiMa after [this coomit](https://github.com/typesafehub/migration-manager/commit/2844ffa48b6d2255aa64bd687703aec21dadd55e) in Akka Build.

Added abstract method test

---

README.md

Link README to sbt plugin wiki page. Fixes #108

---

CONTRIBUTING.md
LICENSE
README.md
core/src/main/resources/LICENSE
core/src/main/scala/com/typesafe/tools/mima/core/util/Urls.scala
project/Build.scala
project/build.properties
project/plugins.sbt
reporter/src/main/resources/LICENSE
sbtplugin/src/main/resources/LICENSE

and throw in some unrelated cleanups while we're at it

upgrade to sbt 0.13.12

---

reporter/functional-tests/src/test/class-method-concrete-override-of-concrete-supertrait-method-ok/v1/A.scala
reporter/functional-tests/src/test/class-method-concrete-override-of-concrete-supertrait-method-ok/v2/A.scala

As questioned in https://github.com/scala/scala/pull/5528

Add test case class-method-concrete-override-of-concrete-supertrait-method

---

project/build.properties
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala

these keys have been deprecated since 0.1.9
fixes #134

remove deprecated stuff

---

CONTRIBUTING.md
README.md

remove references to mima-user

---

README.md
project/Build.scala
project/plugins.sbt

#155 commit removed both s3 publication and assembly task for the cli. 
That PR restore the assembly task part.

Issue #166: restore assembly task removed in #155 along with s3 deploy

---

project/Build.scala
project/build.properties
sbtplugin/src/main/scala-sbt-0.13/compat.scala

and remove the workarounds needed for an older sbt version.

Update to sbt 0.13.16-RC1

---

README.md

remove Eclipse usage instructions

---

.travis.yml
project/Build.scala
project/plugins.sbt

Add, configure & enable MiMa - aka dogfood

---

project/Build.scala

Finish upgrading to Scala 2.12.3

---

core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
reporter/functional-tests/src/it/java-9-module-info/test.conf

Ignore Java 9's CONSTANT_MODULE/CONSTANT_PACKAGE

---

CONTRIBUTING.md
project/Build.scala
project/plugins.sbt

With no CLI, there's no need to assemble anything.

Remove sbt-assembly and sbt-buildinfo

---

CONTRIBUTING.md

Copy what I consider to be the still-relevant parts of #165.

Update the release process

---

.travis.yml
core/src/main/scala-2.13/com/typesafe/tools/mima/core/package.scala
core/src/main/scala-2.13/scala/tools/nsc/mima/package.scala
core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
project/Build.scala

Allow core/compile to pass on Scala 2.13.0-M4

---

.travis.yml
core/src/main/scala/com/typesafe/tools/mima/core/ProblemReporting.scala
core/src/test/scala/com/typesafe/tools/mima/core/ProblemReportingSpec.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala

.. by reworking & moving ProblemReportingSpec from sbtplugin to core.

Drop the need to run "test" cross sbt versions

---

.travis.yml

* run mimaReportBinaryIssues, test, & it:test as one job
* run testFunctional in 2.12, testing 2.11 and 2.12

New CI split

---

.travis.yml

Run it:test on Scala 2.13.0-M4 in CI

---

.travis.yml

Drop sbt 1.0.0 from the test matrix

---

.travis.yml

... and break the build matrix up into sections.

Add the implicit buildScalaVersion in .travis.yml

---

CONTRIBUTING.md
README.md
functional-tests/src/it/java-9-module-info/test.conf
functional-tests/src/test/removing-method-with-special-characters-from-inner-class-nok/v1/A.scala
project/Build.scala

Rename to MiMa

---

functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
functional-tests/src/test/value-class-generic-replacement-false-ok/problems.txt
functional-tests/src/test/value-class-generic-replacement-false-ok/v1/A.scala
functional-tests/src/test/value-class-generic-replacement-false-ok/v2/A.scala

Add a false-ok testcase for value classes in a generic context

---

CONTRIBUTING.md

Resolves #250
Feedback/suggestions welcome.

Document MiMa's self-testing strategy

---

core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
functional-tests/src/test/class-constructor-generics-nok/problems.txt
functional-tests/src/test/class-constructor-generics-nok/v1/A.scala
functional-tests/src/test/class-constructor-generics-nok/v2/A.scala

Add another test case for generics

---

sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala

Normalise previous artifact names

---

README.md
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala

Fix normalizeModuleID usage & doc use of %%

---

README.md
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala

Also bulk-update the README.
Closes #328

Document mimaFailOnNoPrevious & add to error message

---

build.sbt
core/src/main/scala/com/typesafe/tools/mima/core/Config.scala
core/src/main/scala/com/typesafe/tools/mima/core/Members.scala
core/src/main/scala/com/typesafe/tools/mima/core/Settings.scala
core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/ProblemFiltersConfig.scala
project/MimaSettings.scala
project/plugins.sbt

Fix Scala 2.13 warnings

---

README.md
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaKeys.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/ensure-mimaPreviousArtifacts-is-set/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/ensure-mimaPreviousArtifacts-is-set/project/plugins.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/ensure-mimaPreviousArtifacts-is-set/test
sbtplugin/src/sbt-test/sbt-mima-plugin/ensure-mimaPreviousArtifacts-is-set/v1/A.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/ensure-mimaPreviousArtifacts-is-set/v2/A.scala

... using a private instance of empty Set and Map and reference equality.
Fixes #328

Differentiate unset mimaPreviousArtifacts from empty mimaPreviousArtifacts

---

project/MimaSettings.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaKeys.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-abstract-method/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-filters-from-file-wildcard/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/backward-new-inherited-method/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/project/plugins.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/test
sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/v1/A.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/v2/A.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/minimal/build.sbt

And some uninteresting cleanups except, perhaps, the importance/usage-driven sort & re-split of MiMa's keys.

Rescope MiMa's settings, allow for build-level settings!

---

core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
core/src/main/scala/com/typesafe/tools/mima/core/Members.scala
core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
core/src/main/scala/com/typesafe/tools/mima/core/WithLocalModifier.scala
core/src/main/scala/com/typesafe/tools/mima/core/package.scala
core/src/main/scala/com/typesafe/tools/mima/lib/analyze/Analyzer.scala
core/src/main/scala/com/typesafe/tools/mima/lib/analyze/field/FieldChecker.scala
core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodRules.scala
project/MimaSettings.scala

And majorly clean it up, & introduce Methods/Fields private aliases.

Split MemberInfo into MethodInfo/FieldInfo

---

core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
core/src/main/scala/com/typesafe/tools/mima/core/ConstantPool.scala
core/src/main/scala/com/typesafe/tools/mima/core/Definitions.scala

ClassfileParser: cleanup & reorder

---

functional-tests/src/test/public-method-becomes-package-private-nok/problems.txt
functional-tests/src/test/public-method-becomes-package-private-nok/v1/A.scala
functional-tests/src/test/public-method-becomes-package-private-nok/v2/A.scala
functional-tests/src/test/public-method-becomes-package-private-ok/v1/A.scala
functional-tests/src/test/public-method-becomes-package-private-ok/v2/A.scala

Follow-up to #375. 
Is it worth capturing these cases in the test suite?

Add tests for public method becomes private[lib]

---

core/src/main/scala/com/typesafe/tools/mima/core/Settings.scala

before even really delving into what's going on here, it appears to me that maybe this code isn't actually doing anything, and we could just take it out? let's see what CI has to say
fixes #383
UPDATE: CI likes it. @dwijnand skeptical review, please

be compatible with Settings change in Scala 2.12.10

---

project/TestsPlugin.scala

But it requires TupleSyntax :O

Dedup runCollectProblemsTest calls

---

.travis.yml
functional-tests/src/it/scala-library-2-12/test.conf
functional-tests/src/it/scala-library-2-13/test.conf
functional-tests/src/it/scala-reflect-2-12/test.conf
functional-tests/src/it/scala-reflect-2-13/test.conf
functional-tests/src/test/value-class-generic-replacement-ko/problems-2.13.txt

Update to test Scala 2.13.1

---

README.md

README: amend details on sbt versions

---

functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
functional-tests/src/test/class-added-local-class-ok/v1/A.scala
functional-tests/src/test/class-added-local-class-ok/v2/A.scala
functional-tests/src/test/class-removed-local-class-ok/v1/A.scala
functional-tests/src/test/class-removed-local-class-ok/v2/A.scala
functional-tests/src/test/missing-synthetic-classes-are-ignored-ok/v1/A.scala
functional-tests/src/test/missing-synthetic-classes-are-ignored-ok/v2/A.scala
functional-tests/src/test/public-method-becomes-package-private-ok/v1/A.scala
functional-tests/src/test/public-method-becomes-package-private-ok/v2/A.scala
project/TestsPlugin.scala

Initial changes towards running functional tests

---

project/TestsPlugin.scala

TestsPlugin: Extract testCollectProblems

---

README.md
project/MimaSettings.scala

[compare/view]:    https://github.com/lightbend/mima/compare/0.4.0...master
[issues/new]:      https://github.com/lightbend/mima/issues/new
[milestones/list]: https://github.com/lightbend/mima/milestones?direction=asc
[milestones/new]:  https://github.com/lightbend/mima/milestones/new
[prs/list]:        https://github.com/lightbend/mima/pulls
[releases/list]:   https://github.com/lightbend/mima/releases
[releases/new]:    https://github.com/lightbend/mima/releases/new
[RELEASING.md]: https://raw.githubusercontent.com/lightbend/mima/master/RELEASING.md
[repo1/list]: https://repo1.maven.org/maven2/com/typesafe/mima-core_2.12/0.5.0/
[sbt-mima/view]: https://bintray.com/sbt/sbt-plugin-releases/sbt-mima-plugin-imported2/view
[sonatype/guide]: …

Release 0.6.3

---

README.md
project/MimaSettings.scala
project/plugins.sbt

Update sbt-mima-plugin to 0.6.4

---

project/TestsPlugin.scala

A fresh attempt at #403, having understood the problem.  Tested with
it-scala-reflect-2-12 and test-case-class-abstract-becomes-concrete-ok,
by intentionally breaking both and seeing how the tasks failed

Dedup TestsPlugin

---

sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala

Report the summary (previously "found $count potential binary...") at
error or warn level, like the problem details themselves.
Note that `log`, here, is MiMa's Logging interface, which wires its info
level to sbt's _debug_ level.  So logging to "info" will mostly never be
seen.
Therefore, this, in particular, brings to the foreground:
* the module version (".. check against org.scala-sbt:main_2.12:1.1.2!")
* the number of filtered problems (".. (filtered 111)")
Also, don't log the project name with sys.error: sbt's task error
reporting prints the message with the project-specific task name, e.g.:
[error] (mainProj / mimaReportBinaryIssues) Main: Binary compatibility check failed!

Improve problem reporting

---

core/src/main/scala/com/typesafe/tools/mima/lib/MiMaLib.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
project/MimaSettings.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala

Fast-fail on unsupported Scala versions

---

.travis.yml

Just for building and testFunctional, not the integration tests b/c
there's a crazy number of problems/filters to add (ugh).

Scala 2.12.11 & 2.13.2

---

sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala

Just checking if the tests pass for now…

Use CoursierDependencyResolution rather than IvyDependencyResolution

---

README.md

although MY-ma might be more logical, I've never heard anyone say it any other way than MEE-ma
but maybe we should double-check with @dotta :-)

add pronunciation to readme

---

build.sbt
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/AppRunTest.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/IntegrationTests.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/ScalaCompiler.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/Test.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/TestCase.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/TestCli.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/UnitTests.scala
functional-tests/src/test/scala/UnitTestSuite.scala
project/MimaSettings.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala

Reuse maven.version.number when refetching with Coursier

---

core/src/main/scala/com/typesafe/tools/mima/core/util/log/Logging.scala

Make Logging public again

---

functional-tests/src/main/scala/com/typesafe/tools/mima/lib/TestCase.scala

this came up in the Scala community build

source change necessitated by upcoming 2.12.13 change

---

README.md
RELEASING.md
project/MimaSettings.scala
project/plugins.sbt

Release 0.9.0

---

sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/scala-3/build.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/scala-3/project/plugins.sbt
sbtplugin/src/sbt-test/sbt-mima-plugin/scala-3/test
sbtplugin/src/sbt-test/sbt-mima-plugin/scala-3/v1-0-0/src/main/scala/example/Example.scala
sbtplugin/src/sbt-test/sbt-mima-plugin/scala-3/v1-0-1/src/main/scala/example/Example.scala

Fixes #613 See the discussion there.

Fix resolving Scala 3 artifacts

---

core/src/main/scala/com/typesafe/tools/mima/core/MimaUnpickler.scala
functional-tests/src/test/unpickling-name-mangling-ok/app/App.scala
functional-tests/src/test/unpickling-name-mangling-ok/v1/A.scala
functional-tests/src/test/unpickling-name-mangling-ok/v2/A.scala

Fix name mangling for nested classes

---

README.md

this feature was added in #647 (though for Scala 3 only), but never documented

document `mimaExcludeAnnotations`

---

build.sbt
core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
core/src/main/scala/com/typesafe/tools/mima/lib/analyze/Analyzer.scala
functional-tests/src/main/scala/com/typesafe/tools/mima/lib/UnitTests.scala
functional-tests/src/test/changes-in-experimental-objects-are-ok/app/App.scala
functional-tests/src/test/changes-in-experimental-objects-are-ok/testAppRun.pending
functional-tests/src/test/changes-in-experimental-objects-are-ok/v1/A.scala
functional-tests/src/test/changes-in-experimental-objects-are-ok/v1/exclude.scala
functional-tests/src/test/changes-in-experimental-objects-are-ok/v2/A.scala
functional-tests/src/test/changes-in-experimental-objects-are-ok/v2/exclude.scala

- Fix build deprecation
- Fix test deprecation
- Honour outer's exclude annotations

Honour outer's exclude annotations

---

README.md

First attempt to see if @SethTisue is happy with it. :)

Fix #739: Mention TASTy-MiMa in the readme.

---

project/MimaSettings.scala
project/plugins.sbt

Update sbt-mima-plugin to 1.1.3
