lightbend-labs/mima

- .travis.yml
- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- reporter/functional-tests/src/test/java8-turning-interface-method-into-default-method/v1/A.java
- reporter/functional-tests/src/test/java8-turning-interface-method-into-default-method/v2/A.java
I'm surprised that this issue was discovered only now, because we were missing
support for parsing JDK7 classfile (!) - so not just JDK8 ones.
The fix was to simply extend the `ClassfileParser` to consider the additional
constants that may appear in the classfile's Constant Pool.  Because the
implementation of `ClassfileParser` was copied from scalac, we simply applied
here the same fix as in
scala/scala@e78896f#diff-400a2e6482bc824c3840c10ecc43e7b0R140.
We should definitely work on removing this duplication (I'd say it's here for
historical reasons), but doing so is out of the scope of this PR.
> Added support for parsing classfile version 51 (JDK7). Fix #66

- project/Build.scala
In theory, with these changes, to publish `0.1.7` I should:
1) create a tag `0.1.7`
2) run `sbt publish`
@jsuereth Could you confirm?
> Updated build version

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- reporter/functional-tests/src/test/final-class-becomes-object-nok/problems.txt
Constructors are not inherited by subclasses.  Therefore, when looking up a
method to check if it exist in the hierarchy, it's important to filter out
constructors.
> Constructors are not inherited members. Fix #75

- reporter/functional-tests/src/test/class-becomes-object-nok/problems.txt
When fixing #75, I've forgot to update the class-becomes-object-nok test, which
was affected by the changes made to fix the mentioned ticket.
The reason why the CI didn't fail building #75 is that a fix for #82 was only
merged *after* having merged #75.
> Fixed class-becomes-object-nok test. Re #75

- reporter/functional-tests/src/test/class-constructor-inherited-nok/problems.txt
- reporter/functional-tests/src/test/class-constructor-inherited-nok/v1/A.scala
- reporter/functional-tests/src/test/class-constructor-inherited-nok/v2/A.scala
Constructors are special members and are not inherited. Therefore, MiMa needs to
report a binary incompatibility when a constructor is removed from a subclass.
This issue was fixed by e62ef3dc511e39fbeaa73ada5c6e58cfe7ad73a2
> Testing that constructor's methods aren't inherited. Re #75

- .travis.yml
- project/Build.scala
Either change the version from the command line with the property `mima.testScalaVersion` or from
inside sbt with `set testScalaVersion in Global := "someversion"`.
> Enable the MiMa tests to be compiled with a separate Scala version

- project/Build.scala
allowing it to default to "root" leads to this error in the
community build, after extraction:
```
[error] Fatal: multiple projects have the same artifacts visible in the same space.
[error]   root#root  from scala-records and mima, both visible in space "default"
```
perhaps dbuild ought to notice that `publish` and `publishLocal` are
`()` in the root project, but it doesn't (not dbuild 0.9.1 anyway, I
don't know about later versions).  and as far as I can see, setting
the name is harmless.
review by @dotta
> in build, set name of root project

- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/PackageInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/WithLocalModifier.scala
- reporter/functional-tests/src/test/case-class-concrete-becomes-abstract-nok/problems.txt
- reporter/functional-tests/src/test/ignore-changed-and-added-anonymous-lambdas-ok/v1/A.scala
- reporter/functional-tests/src/test/ignore-changed-and-added-anonymous-lambdas-ok/v2/A.scala
- reporter/functional-tests/src/test/ignore-changed-and-removed-anonymous-lambdas-ok/v1/A.scala
- reporter/functional-tests/src/test/ignore-changed-and-removed-anonymous-lambdas-ok/v2/A.scala
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
* Added checks for the Java ACC_SYNTHETIC flag that means that the method isn't accesible from Java source
* Added exception for Java ACC_BRIDGE flag, which is set on erased apply methods together with ACC_SYNTHETIC
* Started using synthetic method name checks, and made them more selective than synthetic field name checks
Fixes #78 (at least the problem described in that ticket)
> Ignore added/removed and changed anonymous lambdas for Scala 2.12.x

- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- reporter/functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- reporter/functional-tests/src/test/case-class-concrete-becomes-abstract-nok/problems.txt
- reporter/functional-tests/src/test/class-becomes-trait-nok/problems.txt
- reporter/functional-tests/src/test/class-changed-val-type-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/class-changed-var-type-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/class-method-abstract-override-of-concrete-superclass-method-nok/problems.txt
- reporter/functional-tests/src/test/class-method-abstract-override-of-concrete-supertrait-method-nok/problems.txt
- reporter/functional-tests/src/test/class-method-changed-parameter-type-nok/problems.txt
- reporter/functional-tests/src/test/class-method-changed-parameters2-nok/problems.txt
- reporter/functional-tests/src/test/class-narrowing-method-type-in-new-version-ok/problems.txt
- reporter/functional-tests/src/test/class-widening-method-type-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/trait-abstract-method-becomes-concrete2-ok/problems.txt
- reporter/functional-tests/src/test/trait-abstract-val-become-concrete-ok/problems.txt
- reporter/functional-tests/src/test/trait-added-method-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/trait-added-val-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/trait-added-var-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/trait-deleting-concrete-methods-is-nok/problems.txt
- reporter/functional-tests/src/test/trait-method-overloading-is-ok/problems.txt
- reporter/functional-tests/src/test/trait-moving-methods-nok/problems.txt
- reporter/functional-tests/src/test/trait-pushing-up-abstract-methods-is-nok/problems.txt
- reporter/functional-tests/src/test/trait-pushing-up-concrete-methods-is-nok/problems.txt
- reporter/functional-tests/src/test/type-parameters-change-breaks-method-signature-nok/problems.txt
- reporter/src/main/scala/com/typesafe/tools/mima/cli/Main.scala
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/Analyzer.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
Rebase of #87 on current master which is now an AutoPlugin.
> Rebase of #87

- .travis.yml
- project/Build.scala
- project/build.properties
- project/plugins.sbt
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/build.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/project/plugins.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/src/main/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/src/v1/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/src/v2/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/backward-multiple-versions/test
- sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/build.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/project/plugins.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/src/main/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/src/v1/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/src/v2/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/forward-multiple-versions/test
- sbtplugin/src/sbt-test/sbt-mima-plugin/minimal/build.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/minimal/project/plugins.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/minimal/src/main/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/minimal/src/v1/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/minimal/test
Limiting which filters apply to which version is very useful when issue filter list becomes large and BC is being checked among multiple versions.
For example there were lots of BC issues that needed to be ignored between Akka 2.3.14 and 2.4.0. However from 2.4.0 onwards there are little or no BC issues so filtering should be kept at minimum to prevent false positive BC reports.
This change is already being used in https://github.com/akka/akka/pull/17761.
This PR also adds two scripted tests for the sbt plugin.
> Add versioned issue filters

- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodRules.scala
By using abstract classes, it is possible to preserve the
functionality of existing problem filters from previous versions.
> Fix for AbstractMethodProblem and MissingMethodProblem matching

- project/Build.scala
context: trying to move projects in the Scala community build to the
latest Specs2 so we can eventually retire 2.x
> remove unused specs2 dependency

- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
This might not be 100% correct, if there are legitimate alternative
classifiers that are used for binary classfiles (as opposed to sources
and javadocs, which is Scala source files and Javadoc HTML files).
But this is a quick 98% fix, imo.
> Specify that artifact.classifier must be empty. Fixes #124

- .travis.yml
- build.sbt
- project/Build.scala
- project/build.properties
Migrate from the Build trait, the fishbone operators and tuple enrichment syntax.
To avoid bike shedding arguments holding up this PR I've gone for a (mostly) minimal-diff approach.
> Upgrade to sbt 0.13.13-RC3

- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
This tiny patch attempts to fix a thread-safety issue which causes various class file parsing errors when MiMa is run concurrently on multiple SBT subprojects (see #115 and #112).
The singleton `ClassInfo.ObjectClass` object can be used by multiple threads and it contains a `ClassFileParser` instance which is not thread-safe. I believe that synchronizing `parse()`, the only (logically) public method of `ClassFileParser`, should be a minimal fix.
For the investigation that prompted this PR, see https://github.com/typesafehub/migration-manager/issues/115#issuecomment-251879851.
> Synchronize ClassfileParser.parse() in attempt to prevent parsing errors in concurrent runs

- reporter/src/main/scala/com/typesafe/tools/mima/cli/Main.scala
Since 2844ffa4, running MiMa from the CLI has been a no-op unless
the new option `--direction backwards` was provided. Only the SBT
plugin correctly used the default value.
Noticed in the SBT build of Scala on the 2.12.x branch, where
we use MiMa be calling `Main.main` from our build for some reason,
rather than using the SBT plugin directly.
This commit restores the old behaviour when that parameter is
missing, as manually tested with:
```
% sbt reporter/runMain com.typesafe.tools.mima.cli.Main --prev /Users/jz/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.0-RC1.jar --curr /Users/jz/code/scala/build/pack/lib/scala-library.jar
[info] Compiling 1 Scala source to /Users/jz/code/migration-manager/reporter/target/scala-2.10/classes...
[info] Running …
```
> Fix default value of --direction in CLI

- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- reporter/functional-tests/src/test/value-class-added-concrete-method-nok/problems.txt
- reporter/functional-tests/src/test/value-class-added-concrete-method-nok/v1/A.scala
- reporter/functional-tests/src/test/value-class-added-concrete-method-nok/v2/A.scala
They are classified as “has a synthetic name” (i.e. contains a “$”) but
regular use of these methods generates calls to the names from other
compilation units.
Fixes #135.
> Do not skip extension methods.

- .gitignore
- project/Build.scala
- Ignore .idea dirs (there’s already a bunch of Eclipse-specific
patterns in .gitignore)
- Require that test dirs contain a “problems.txt” file. When switching
between branches with different tests, you’re left with empty dirs
under reporter/src/test. They used to be picked up as tests (which
subsequently failed because they are not).
> Make life easier for developers

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Members.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- reporter/functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- reporter/functional-tests/src/test/java-class-missing-static-method-in-new-version-nok/problems.txt
- reporter/functional-tests/src/test/java-class-missing-static-method-in-new-version-nok/v1/A.java
- reporter/functional-tests/src/test/java-class-missing-static-method-in-new-version-nok/v2/A.java
- reporter/functional-tests/src/test/java-class-static-to-virtual-method-nok/problems.txt
- reporter/functional-tests/src/test/java-class-static-to-virtual-method-nok/v1/A.java
- reporter/functional-tests/src/test/java-class-static-to-virtual-method-nok/v2/A.java
- reporter/functional-tests/src/test/java-class-virtual-to-static-method-nok/problems.txt
- reporter/functional-tests/src/test/java-class-virtual-to-static-method-nok/v1/A.java
- reporter/functional-tests/src/test/java-class-virtual-to-static-method-nok/v2/A.java
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/field/FieldChecker.scala
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- reporter/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodRules.scala
We can reliably/simply determine whether a class if from scalac
by the presence/absense of Scala/ScalaSig attributes. With this
knowledge, we can include static methods from non Scala classfiles
into MiMa's purview.
I've added specific code to warn about static <-> non-static changes,
which aren't binary compatible. In addition, the existing rules will
now run for these members.
In order to make this work, we also need to skip static members in
Scala classes after parsing attributes
Two other problems discovered and fixed while implementing this:
- `Members.members` is only a `TraversableOnce` which is traversed in
the constructor. It should not be exposed as a field.
- The now inlined methods `parseFields` and `parseMethods` in
`ClassfileParser` did not always skip the members in the …
> Add support for Java-defined static members

- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- reporter/functional-tests/src/test/class-method-overload-with-default-parameters-nok/problems.txt
- reporter/functional-tests/src/test/class-method-overload-with-default-parameters-nok/v1/A.scala
- reporter/functional-tests/src/test/class-method-overload-with-default-parameters-nok/v2/A.scala
They are called from other compilation units and their names can change
when a new overload is added to a method with default values.
Fixes #136.
> Treat default value getters as accessible.

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- core/src/main/scala/com/typesafe/tools/mima/core/PackageInfo.scala
- reporter/functional-tests/src/test/class-added-local-class-ok/v1/A.scala
- reporter/functional-tests/src/test/class-added-local-class-ok/v2/A.scala
- reporter/functional-tests/src/test/class-changed-local-class-ok/v1/A.scala
- reporter/functional-tests/src/test/class-changed-local-class-ok/v2/A.scala
- reporter/functional-tests/src/test/class-removed-local-class-ok/v1/A.scala
- reporter/functional-tests/src/test/class-removed-local-class-ok/v2/A.scala
If a class has the `EnclosingMethod` attribute, we know it was defined
in the body of a method (or a val/var initializer), and is not part of
the API of a class.
Fixes #147
Review by @szeiger. Sorry I didn't pick this up in my review!
> Avoid false positives for classes defined in methods

- core/src/main/scala/com/typesafe/tools/mima/core/PackageInfo.scala
- reporter/functional-tests/src/test/removing-method-with-special-characters-from-inner-class-nok/problems.txt
- reporter/functional-tests/src/test/removing-method-with-special-characters-from-inner-class-nok/v1/A.scala
- reporter/functional-tests/src/test/removing-method-with-special-characters-from-inner-class-nok/v2/A.scala
We used to skip all classes whose bytecode name contains “$$” under the
assumption that those would be names with synthetic components like
“$$anonfun” but these names can also occur when a class name starting
with a symbolic character is nested inside an object (e.g. “A$$less” is
a class named “<“ inside an “object A”). Instead we need to look at the
decoded names. They still contain synthetic components such as
“$$anonfun” verbatim but no accidental “$$” sequences.
Fixes #158.
> Do not skip classes with symbolic names in objects

- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
This fixes the problem where mima check in the Akka build would run out of memory (with 2GB heap). Akka has many artifacts and checks BC between quite a few minor versions.
> Report found problems as they are returned instead of collecting

- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/Keys.scala
This will allow to load the filter definitions from something else than
source code without having to reload the project after having changed the
filters.
We are currently experimenting with moving the filters to external files so that the filters don't have to be compiled so often (IIRC big `Seq(...)` expressions can be quite costly for type inference). See https://github.com/akka/akka-http/pull/677. If that approach works well it might make sense to move it here as well.
> convert filter definitions to taskKeys

- core/src/main/scala/com/typesafe/tools/mima/core/Filters.scala
- core/src/test/scala/com/typesafe/tools/mima/core/ProblemFiltersSpec.scala
- project/Build.scala
- reporter/functional-tests/src/it/scala-reflect-2-10/test.conf
- reporter/functional-tests/src/it/scala-reflect-2-11/test.conf
- reporter/functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- reporter/src/main/scala/com/typesafe/tools/mima/cli/ProblemFiltersConfig.scala
Add problem filter by the start of the FQCN. Can be used like so:
ProblemFilters.excludeStartingWith[Problem]("akka.cluster.pubsub.DistributedPubSubMediator$Internal")
Also, I realised that `FilterAnyProblem` mentioned in #171 is not really needed as that is the same as, for example:
ProblemFilters.exclude[Problem]("akka.http.javadsl.model.Uri")
Fixes #171
> #171 Wildcard support in exclude problem filter

- core/src/main/scala/com/typesafe/tools/mima/core/Filters.scala
- core/src/test/scala/com/typesafe/tools/mima/core/ProblemFiltersSpec.scala
- project/Build.scala
- reporter/functional-tests/src/it/scala-reflect-2-10/test.conf
- reporter/functional-tests/src/it/scala-reflect-2-11/test.conf
- reporter/functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- reporter/src/main/scala/com/typesafe/tools/mima/cli/ProblemFiltersConfig.scala
Filter file is a different format from the one that is supported by the CLI. A different format was chosen partly because it is less verbose and partly because such format is already used in akka-http.
Builds on top #172
Fixes #170
> Filters from file support in sbt plugin

- reporter/src/main/scala/com/typesafe/tools/mima/cli/Main.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
MiMaLib accumulates problems in a [mutable list buffer](https://github.com/typesafehub/migration-manager/blob/f147e625781d3ddfafb3897120874dce0993ec20/reporter/src/main/scala/com/typesafe/tools/mima/lib/MiMaLib.scala#L37). Therefore we need to create a new MiMaLib instance between checking for backward and forward BC problems.
This change is required to be able to check for BC probems in `both` directions (like in Scala).
> Get new instance of mutable mima instance

- core/src/main/scala-2.12/com/typesafe/tools/mima/core/package.scala
- reporter/functional-tests/src/test/package-nested-with-breaking-change-is-nok/problems.txt
- reporter/functional-tests/src/test/package-nested-with-breaking-change-is-nok/v1/A.scala
- reporter/functional-tests/src/test/package-nested-with-breaking-change-is-nok/v2/A.scala
This was causing no class to be found (!!) because it would define the
package as "pp.q" instead of "p.q".
> Fix package name for nested packages, in 2.12

- project/Build.scala
- project/plugins.sbt
Fixes #133, and simplifies the release process at
https://github.com/typesafehub/migration-manager/wiki/Releasing-MiMa
> Add sbt-pgp & disable publishSigned for the root

- .travis.yml
- project/Build.scala
- project/build.properties
- sbtplugin/src/main/scala-sbt-0.13/compat.scala
+ upgrade to Scala 2.11.11
+ upgrade to Scala 2.12.3 (refs #191)
+ upgrade to sbt 0.13.16/1.0.0-RC3
+ cross-build against 0.13.13 instead of 0.13.16 (fixes #183)
> Version updates and changes

- CONTRIBUTING.md
- README.md
so we can shut down the wiki
fixes #199
> merge wiki contents into README.md and CONTRIBUTING.md

- core/src/main/scala/com/typesafe/tools/mima/core/util/log/ConsoleLogging.scala
- core/src/main/scala/com/typesafe/tools/mima/core/util/log/Logging.scala
- project/Build.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
- sbtplugin/src/test/scala/com/typesafe/tools/mima/plugin/ProblemReportingSpec.scala
> Add support for versions with less segments (#212)

- reporter/functional-tests/src/test/case-class-constructor-becomes-private-ok/v1/A.scala
- reporter/functional-tests/src/test/case-class-constructor-becomes-private-ok/v2/A.scala
Noticed this in the wild. This change is not source compatible but is binary compatible.
> Add a functional test where case class constructor becomes private

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
- core/src/test/scala/com/typesafe/tools/mima/core/ProblemReportingSpec.scala
This removes a use of null, and makes NoClass not fall over so easily,
such as in ProblemReportingSpec, where I can switch to using it.
> Fix NoClass, use NoPackageInfo over null

- .travis.yml
These are equivalent to:
- TEST_COMMAND="sbt -Dmima.buildScalaVersion=2.12.7 -Dmima.testScalaVersion=2.12.7 testFunctional"
- TEST_COMMAND="sbt -Dmima.buildScalaVersion=2.13.0-M5 -Dmima.testScalaVersion=2.13.0-M5 testFunctional"
and are leftovers from when the build would default to scala version 2.10
> Remove redundant testFunctional calls

- reporter/functional-tests/src/test/inner-class-loses-outer-pointer-ko/problems.txt
- reporter/functional-tests/src/test/inner-class-loses-outer-pointer-ko/v1/A.scala
- reporter/functional-tests/src/test/inner-class-loses-outer-pointer-ko/v2/A.scala
Test case for https://github.com/scala/scala-dev/issues/627
> Inner class loses outer pointer test-case

- project/Build.scala
This makes the reflection usage compatible with Java 11, where
Class#newInstance is deprecated (and we have fatal warnings enabled in
the meta-build).
> Use Class#getDeclaredConstructor()#newInstance()

- build.sbt
- project/TestsPlugin.scala
This is for dbuild compatibility: https://github.com/scala/community-builds/pull/926
> Reconfigure functional tests to use the test key

- README.md
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaKeys.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
> Undeprecate mimaFailOnNoPrevious to build-wide opt-out

- RELEASING.md
Also switch to sending a PR for the post-release updates, not because
pushing to master isn't so strictly prohibited, but to use to verify
when the release has synced in Maven Central.
> Update the release proc to include resetting MiMa

- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- functional-tests/src/it/scala-library-2-11/test.conf
- functional-tests/src/it/scala-reflect-2-10/test.conf
- functional-tests/src/it/scala-reflect-2-11/test.conf
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- project/TestsPlugin.scala
Instead of taking the first method which "matches type" (which actually 
means "has the same parameters") to check whether the result types also 
match, check them all.
The impact is visible in the integration test changes: ZipArchive's 
underlyingSource is "just" a (generic) signature problem, not a result type
problem.  Specifically it still returns a scala.Some, except it's a:
> ()Lscala/Some<Lscala/reflect/io/AbstractFile;>; rather than
()Lscala/Some<Lscala/reflect/io/ZipArchive;>;
... preceeded by a CollectProblemsTest improvement, a functional test setup fix & cleanup.
> Verify all overloads for result types & signatures

- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- core/src/main/scala/com/typesafe/tools/mima/core/ConstantPool.scala
Even though it's intimately related to the class file parser, it's a
large enough piece of behaviour, which is already a distinct class, that
it's reasonable to think about dealing with as a standalone "thing".
> Move ConstantPool out of ClassfileParser

- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- core/src/test/scala/com/typesafe/tools/mima/core/ProblemFiltersSpec.scala
- project/MimaSettings.scala
Using pattern matching to define "description" moves the implementation
a little away from each Problem class definition.  However, overall the
file shrinks and now the problem descriptions can be made more uniform
by comparison.
> Sort, group & cleanup Problems

- build.sbt
With sbt-travisci it picked 2.13.0, which doesn't work nicely as the
sbtplugin doesn't support it.
> Set the default scalaVersion back to 2.12.8

- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- functional-tests/src/test/class-removed-method-overload-ko/problems.txt
- functional-tests/src/test/class-removed-method-overload-ko/v1/A.scala
- functional-tests/src/test/class-removed-method-overload-ko/v2/A.scala
Previously the method checker didn't take overloading into account, which
means that the loss of a method overload (which includes the loss of a
static forwarder method overload, such as when upgrading from Scala 2.12.7 to 2.12.8+) was
reported as an "incompatible method type" problem or a
"incompatible result type" problem.
With this change these are now correctly reported as "direct missing 
method" problems.
> Removed overloads are missing, not incompatible

- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- functional-tests/src/it/scala-library-2-12/test.conf
- functional-tests/src/test/class-removed-method-overload-ko/problems.txt
- functional-tests/src/test/class-removed-method-overload-ko/v1/A.scala
- functional-tests/src/test/class-removed-method-overload-ko/v2/A.scala
- project/TestsPlugin.scala
Refs #361 ("X has a different signature in current version").
Builds on #362 ("Removed overloads are missing, not incompatible").
These are all the problems in the 2.12.x series of scala-library, including all the currently reported incompatible signature problems - all of which are false-positives.
See #335 and #363 for some proposed enhancements to remove some cases of false positives.
The advice on `IncompatibleSignatureProblem` is that it can false positive:
* if you'd like to use it to help you identify possible incompatible changes (non-LinkageError incompatibilities) then manually filter the false positives;
* if, instead, you don't want the reports (whether they're true positives or false positives) then use `ProblemFilters.exclude[IncompatibleSignatureProblem]("*")` to filter …
> Test latest scala-library 2.12.9, analysed

- build.sbt
- core/src/test/scala/com/typesafe/tools/mima/core/ProblemFiltersSpec.scala
- core/src/test/scala/com/typesafe/tools/mima/core/ProblemReportingSpec.scala
I think we had moved to 3.1.x because there was an interval when
3.0.x wasn't available for whatever Scala 2.13 prerelease is current
at the time. that consideration no longer applies.
in the community build, we're still on ScalaTest 3.0 (since 3.1 isn't
final yet), so I'd rather do the downgrade here for now, rather than
have to freeze mima in the community build (which is what we've done
with some other projects that have moved to 3.1)
> downgrade ScalaTest to 3.0.x, for community build

- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- functional-tests/src/test/class-constructor-generics-nok/problems.txt
- functional-tests/src/test/class-method-generics-nok/problems.txt
- functional-tests/src/test/class-method-generics-nok/v1/A.scala
- functional-tests/src/test/class-method-generics-nok/v2/A.scala
Also adds a API vs ABI example showing how we can't assume that losing a signature is safe.
> Use <missing> rather than [N/A] for missing signatures

- build.sbt
- core/src/main/scala/com/typesafe/tools/mima/core/ProblemFilters.scala
- core/src/main/scala/com/typesafe/tools/mima/core/package.scala
I got the following warnings while releasing 0.6.1:
```
[warn] /d/mima/core/src/main/scala/com/typesafe/tools/mima/core/package.scala:13:40: constructor PathResolver in class PathResolver is deprecated (since 2.12.9): for bincompat in 2.12.x series
[warn]     AggregateClassPath.createAggregate(new PathResolver(Config.settings).containers: _*)
[warn]                                        ^
[warn] /d/mima/core/src/main/scala/com/typesafe/tools/mima/core/package.scala:32:40: constructor ClassPathFactory in class ClassPathFactory is deprecated (since 2.12.9): for bincompat in 2.12.x series
[warn]     AggregateClassPath.createAggregate(new ClassPathFactory(Config.settings).classesInPath(cpString): _*)
[warn]                                        ^
[warn] …
```
> Fix warnings

- build.sbt
Defining "sbt.boot.directory" makes the scripted test (re)use the same 
user-shared compiler bridge instead of compiling one every time.
Also drop running "Test / compile".
~Builds on #400 just because it's modifying an adjacent line in build.sbt.~
> Speed-up scripted

- .travis.yml
- build.sbt
- project/MimaSettings.scala
This drops the setup & testing of MiMa using Scala 2.13.
The reason is that there is no need for this.  MiMa is by-and-large
consumed via its sbt plugins, which is not 1.x only.  sbt 1.x will
always be Scala 2.12 only, and there are not real plans for sbt 2.x.
Therefore we can stop building with Scala 2.13.
Note that MiMa continues to support verifying the binary compatibility
of Scala 2.11-2.13 projects - that support is crucial and not going
anywhere.
> Drop building in Scala 2.13

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Config.scala
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
That classpath is only used to define ClassInfo.ObjectClass, so:
1. don't make it a var and redefine it
2. localise its usage
> Drop Config.baseClassPath/baseDefinitions (var!)

- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
In #362 I changed the logic so that when an overloaded is dropped it 
doesn't get reported as an "incompatible method type" or "incompatible 
result type" problem.
Looking back the logic is quite short-sighted.
So here I attempt to make it more straight-forward: if there were 
overloads, then the method is missing - it's not incompatible.
(Split into 2 commits.)
> Reimplement problem discovery for dropped overload

- build.sbt
- functional-tests/src/it/scala-library-2-13/test.conf
Upgrading to sbt 1.3 (and, therefore, switching from Ivy to Coursier) broke how the integration tests work, as only 2.12 scala-library is used instead of 2.10-2.13 libraries (scala-reflect is fine):
* before 1.3 https://travis-ci.org/lightbend/mima/jobs/575703798#L285-L287
* after 1.3 https://travis-ci.org/lightbend/mima/jobs/581142473#L410-L413
As a result, setting `useCoursier := false` results in:
```
com.typesafe.tools.mima.lib.CollectProblemsTest$TestFailed: 'it-scala-library-2-13' failed.
The following 22 problems were reported but not expected:
- class scala.collection.ArrayOps#GroupedIterator is declared final in new version
- method nullSlotAndCopy(Array[Array[java.lang.Object]],Int,Array[java.lang.Object])Array[java.lang.Object] in class scala.collection.immutable.VectorBuilder …
```
> Fix integration tests

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
def isClass = !isTrait && !isInterface
Therefore
isClass || isInterface
(!isTrait && !isInterface) || isInterface     inline isClass
isInterface || (!isTrait && !isInterface)     flip ||
isInterface || !isTrait                       subsume !isInterface
But given the precending `if (isTrait)` it's really
isTrait || isInterface || !isTrait
therefore it can be simplified to just isInterface.
> Simplify ClassInfo#concreteMethods

- CONTRIBUTING.md
- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- functional-tests/src/test/class-method-implementation-result-type-changed-nok/app/App.scala
- functional-tests/src/test/class-method-implementation-result-type-changed-nok/problems.txt
- functional-tests/src/test/class-method-implementation-result-type-changed-nok/v1/Foo.scala
- functional-tests/src/test/class-method-implementation-result-type-changed-nok/v2/Foo.scala
- functional-tests/src/test/class-method-result-type-changed-nok/app/App.scala
- functional-tests/src/test/class-method-result-type-changed-nok/problems.txt
- functional-tests/src/test/class-method-result-type-changed-nok/v1/Foo.scala
- functional-tests/src/test/class-method-result-type-changed-nok/v2/Foo.scala
Partly reverting b58ed45f3940e0ae8e8215b253b68ab1acdb3f18
Refs #459
> Correctly classify incompatible result types of overridden methods

- functional-tests/src/test/class-method-result-type-changed-nok/app/App.scala
This test was supposed to test that running this code, compiled against v1,
against v2, would indeed fail.
Unfortunately it didn't have the expected class name, so it already failed
for that reason.
> Fix 'ResultTypeChanged' negative compilation test

- project/TestsPlugin.scala
Make App & Test use the same mainClass.  Actually allow it to be called
anything (though "App" is now the tradition).
Also run in the same way, without trapping exit.
> build: Sync the setup of App & Test more

- README.md
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaKeys.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/test
- sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/v1/A.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/build-level-keys/v2/A.scala
Set `ThisBuild / mimaReportSignatureProblems := true` to opt-in.
TODO:
> Make signature problems opt-in

- functional-tests/src/test/object-loses-type-alias-ok/app/App.scala
- functional-tests/src/test/object-loses-type-alias-ok/v1/A.scala
- functional-tests/src/test/object-loses-type-alias-ok/v2/A.scala
Type aliases can't be top-level (in the normal way, not in the Dotty
way) because that type definition must live in some bytecode somewhere.
So I wanted to check that that doesn't have any binary compatibility
concerns if you lose the alias.  (In truth I was double-checking
https://github.com/scala/bug/issues/11888#issuecomment-590302431).
> Add test object-loses-type-alias-ok

- core/src/main/scala/com/typesafe/tools/mima/core/package.scala
- core/src/main/scala/com/typesafe/tools/mima/lib/MiMaLib.scala
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- functional-tests/src/test/class-method-del-override-from-Throwable-ok/app/App.scala
- functional-tests/src/test/class-method-del-override-from-Throwable-ok/problems.txt
- functional-tests/src/test/class-method-del-override-from-Throwable-ok/v1/A.scala
- functional-tests/src/test/class-method-del-override-from-Throwable-ok/v2/A.scala
- project/MimaSettings.scala
- project/TestsPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
Previously CollectProblemsTest (which runs is used to run the test
suite) appended Config.baseClassPath at the end of the test classpath,
while SbtMima didn't.  This lead to a false positive around types like
Throwable.
After verifying that the problem presents itself by removing the
baseClassPath, I fixed the bug by pushing this setup into the shared
MiMaLib, thus removing it as a difference between SbtMima and
CollectProblemsTest.
Fixes #477
> Fix classpath handling in MiMaLib/SbtMima/CollectProblemsTest

- core/src/main/scala/com/typesafe/tools/mima/core/Config.scala
`sbt mimaReportBinaryIssues` is terminating the sbt process with `System.exit(-1)`.
```
sbt:lib-weepickle-spices-parsers-play25-v1> mimaReportBinaryIssues
not a directory or jar file: /Users/doug.roper/code/lib-weepickle-spices/parsers-play25/target/scala-2.11/classes
$
```
Similar error condition to #55, but this PR is about preventing shutdown of the sbt's JVM when a mima problem occurs.
We've [forked mima](https://github.com/rallyhealth/sbt-git-versioning/blob/43301a1108112818f56e7de2abeb034394e94f4f/src/main/scala/com/rallyhealth/sbt/semver/CustomMiMaLibMiMaExecutor.scala#L14-L37) over this issue, but I'd like to get us back on mainline.
I've verified this manually using a snapshot:
```
sbt:lib-weepickle-spices> parsers-play25/mimaReportBinaryIssues
[error] stack trace is suppressed; …
```
> Replace sys.exit(-1) with sys.error(msg)

- .travis.yml
MiMa uses nsc's ClassPath, which has code JDK 9+'s JRT classpath.
So I'm thinking it would be good to test on both Java 8 and 11.
> Add OpenJDK 11

- core/src/main/scala/com/typesafe/tools/mima/lib/MiMaLib.scala
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- project/TestsPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
In TestsPlugin I was trying to drop the:
val cp = (functionalTests / Compile / fullClasspath).value // the test classpath from the functionalTest project for the test
val si = (functionalTests / scalaInstance).value // get a reference to the already loaded Scala classes so we get the advantage of a warm jvm
for just making the functional projects use their own scalaInstance and just regular project dependsOn functionalTests.  But it turns out that that makes the tests take 80s seconds instead of 30s (even with classloader caching improvements in recent versions of sbt).  Oh well.
> Misc: move Scala version check, fix log & formatting

- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtLogger.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
This used to be possible (i.e.
https://github.com/akka/akka-http/blob/master/project/ValidatePullRequest.scala#L562)
by creating an instance of SbtLogger, which was
(correctly) made private[plugin] in 67fb8d46c53ffc43756e9aea00bea6db5b05ecc2.
This cleans up the SbtMima API so no now-internal API's are needed to call it.
> Allow calling SbtMima.runMima from other plugins

- .travis.yml
Previously the setup created two "sbt ++$TRAVIS_SCALA test" build jobs,
for openjdk8 and openjdk11, and then the rest of the jobs in the "jobs"
section (once, on openjdk8 - because it's the first jdk value).
Now it will run the whole test/mimaReportBinaryIssues/etc job once on
Java 8 and once on Java 11, and then testFunctional/etc on Java 8 (like
before).
> Drop a redundant Travis CI job

- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- core/src/test/scala/com/typesafe/tools/mima/lib/analyze/method/MethodCheckerSpec.scala
- functional-tests/src/test/class-method-generics-nok/problems.txt
- functional-tests/src/test/class-method-generics-nok/v2/A.scala
- functional-tests/src/test/type-parameter-names-change-ok/app/App.scala
- functional-tests/src/test/type-parameter-names-change-ok/v1/Tree.scala
- functional-tests/src/test/type-parameter-names-change-ok/v2/Tree.scala
- project/MimaSettings.scala
Avoids false positive when only the names are changed
Fixes the 'rename' (but not 'reorder') part of #363
> Parse signatures to avoid false positives

- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- core/src/main/scala/com/typesafe/tools/mima/core/MemberInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Signature.scala
- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- core/src/test/scala/com/typesafe/tools/mima/core/SignatureSpec.scala
> Move signature logic to its own class

- README.md
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
See the discussion in https://github.com/lightbend/mima/issues/168. Non-normalized names can't be resolved on their own later on, I don't think there's a point in normalizing them here.
> Don't normalize names

- build.sbt
The original issue is gone now that the jars are resolved
programmatically (also using Coursier, in `IntegrationTests`).
> Switch the build to useCoursier!

- .sbtopts
I'm experimenting with a snapshot build of MiMa, using `export
SBT_OPTS=-Dsbt.version=1.4.0-SNAPSHOT` to select it (so I don't
accidentally commit the build.properties change).  Can Zinc build on
Travis CI without it, in 2020?
> Remove .sbtopts

- project/plugins.sbt
4.1.0 had a bug (dwijnand/sbt-dynver#169) which turned up in the Scala
community build, 4.1.1 fixes it
> bump sbt-dynver version

- core/src/main/scala/com/typesafe/tools/mima/core/ClassInfo.scala
- core/src/main/scala/com/typesafe/tools/mima/core/Problems.scala
- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala
- functional-tests/src/it/scala-library-2-13/problems.txt
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/CollectProblemsTest.scala
- functional-tests/src/test/trait-adding-a-method-override-is-nok/app/App.scala
- functional-tests/src/test/trait-adding-a-method-override-is-nok/forwards.txt
- functional-tests/src/test/trait-adding-a-method-override-is-nok/v1/A.scala
- functional-tests/src/test/trait-adding-a-method-override-is-nok/v2/A.scala
- functional-tests/src/test/trait-deleting-concrete-methods-is-nok/problems.txt
- functional-tests/src/test/trait-inheriting-from-class-nok/problems.txt
- functional-tests/src/test/trait-pushing-up-concrete-methods-is-nok/problems.txt
Refs https://github.com/scala/bug/issues/12137
> Catch forward-incompatible method overriding in traits

- project/MimaSettings.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala
... instead of reinventing a variant of it.
Fixes #550
> Use sbt (1.0's!) dependencyResolution

- core/src/main/scala/com/typesafe/tools/mima/core/ClassPath.scala
A `newDirectoryStream` must be closed after reading. We can do that
immediately because we're sorting the list so we have to consume
the entire stream anyway.
> Close classpath directory after listing

- core/src/main/scala/com/typesafe/tools/mima/core/ClassPath.scala
or sometime after 11, anyway
this turned up in the Scala community build.
> resolve ambiguity introduced by JDK 14

- .travis.yml
To deal with the sudden break in repo.scala-sbt.org usage. https://github.com/scala/scala-dev/issues/765
> Get latest sbt-extras

- build.sbt
- core/src/main/scala/com/typesafe/tools/mima/core/PackageInfo.scala
The sbt plugin stays on Scala 2.12 as sbt 1.x does.
I needed to adapt one source file to the new collection API and introduced new dependency `scala-collection-compat` which provides said new API to the older collections.
Fix https://github.com/lightbend/mima/issues/617
> Enabled cross build with Scala 2.13 for core and functional-tests

- build.sbt
- core/src/main/scala/com/typesafe/tools/mima/core/PackageInfo.scala
this is easier than arguing with dbuild about conflicting cross-version suffixes over at https://github.com/scala/community-build/pull/1407
> remove dependency on scala-collection-compat

- core/src/main/scala/com/typesafe/tools/mima/core/ClassfileParser.scala
- core/src/main/scala/com/typesafe/tools/mima/core/MimaUnpickler.scala
- core/src/main/scala/com/typesafe/tools/mima/core/PickleBuffer.scala
- core/src/main/scala/com/typesafe/tools/mima/core/PickleFormat.scala
- project/MimaSettings.scala
I hoped to be able to completely handle this without unpickling the
types.  The reported case pushed me to exploring it, but when I realised
it would require reimplementing erasure logic I backed out again.
Fixes #630
> Ignore pickle/bytecode method mismatch

- core/src/main/scala/com/typesafe/tools/mima/core/MimaUnpickler.scala
> More unpickling fixes

- build.sbt
- core/src/main/scala/com/typesafe/tools/mima/core/MimaUnpickler.scala
- core/src/main/scala/com/typesafe/tools/mima/core/PicklePrinter.scala
- core/src/main/scala/com/typesafe/tools/mima/core/ProblemReporting.scala
- core/src/main/scala/com/typesafe/tools/mima/core/TastyFormat.scala
- core/src/main/scala/com/typesafe/tools/mima/lib/analyze/field/FieldChecker.scala
References https://github.com/scala/scala-dev/issues/769#issuecomment-928318959
> Enable -Xsource:3 and reduce noise

- sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/MimaPlugin.scala
See https://github.com/slick/slick/pull/2356, https://github.com/scalacenter/sbt-version-policy/issues/119, https://github.com/scalacenter/sbt-version-policy/pull/121
Basically, while I want to use MiMa the way most people do, to make sure version bumps are the correct bump type, I also want to generate a report of changes (and not by the widespread "solution" of encoding the changelog as MiMa filters). This means that while the "real" SBT setting may be a check direction of `"none"`, or with sbt-version-policy the `versionPollcyIntention` may be `Compatibility.None`, I still want to have the ability to run MiMa and get back information that I can present in an arbitrary format to the user. It just shouldn't break the build.
I first implemented a PR generating a markdown report for Slick …
> Allow checking in an on-the-fly mode while still benefiting from other sbt settings

- build.sbt
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/Test.scala
- project/plugins.sbt
Opening PR for fun, after a discussion with @keynmol in the #tooling channel on Discord.
However, this basically required no changes and at least the core tests are passing. Maybe some interesting tooling could be built on this.
> Cross-compile for Native

- build.sbt
- functional-tests/src/main/scala/com/typesafe/tools/mima/lib/TestCli.scala
not waiting for the steward, because I'm investigating a community build failure over at https://github.com/scala/community-build/pull/1606 and I'm curious to see if CI likes this here
> Scala 2.13.10 (was .8)

- README.md
Mention https://github.com/lolgab/mill-mima (MiMa plugin for Mill) in the README.
I separated the usage into a "SBT" part and a tiny "Mill" section. Maybe you would prefer another structure since this repository is mostly about the core and SBT plugin rather than the Mill support.
References #744
> Mention MiMa-Mill in README.md

- core/src/main/scala/com/typesafe/tools/mima/lib/MiMaLib.scala
References #702.
I don't know much about MiMa's internals.  This may be nonsense, but it fixes https://github.com/typelevel/otel4s/pull/122.
> Handle POM-only modules by creating empty Definitions

- build.sbt
- don't pass unsupported options to Scala 3 compiler
- set versionScheme
> build tweaks

- core/src/main/scala/com/typesafe/tools/mima/lib/MiMaLib.scala
- sbtplugin/src/sbt-test/sbt-mima-plugin/pom-only-project/build.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/pom-only-project/project/plugins.sbt
- sbtplugin/src/sbt-test/sbt-mima-plugin/pom-only-project/test
References #768, #702, #743
Like @rossabaker in #743, I also don't know much about MiMa's internals, but from what I've poked around at, this seems to make sense?
> use the same base classpath for empty packages as is used for normal packages

- README.md
- build.sbt
- cli/src/main/scala/com/typesafe/tools/mima/cli/MimaCli.scala
- cli/src/main/scala/com/typesafe/tools/mima/cli/ProblemFormatter.scala
See https://github.com/lightbend-labs/mima/discussions/701.
Early state, probably should get at least a README. The code is pretty much a verbatim copy of https://github.com/jeremyrsmith/mima-cli/ (licensed under Apache 2.0, I'm not sure what the preferred protocol is for adding a notice here).
> Add MiMa CLI
